[phases.setup]
nixPkgs = ['dotnet-sdk_8']

[phases.build]
cmds = [
  'cd TheMindSpire',
  'dotnet restore',
  'dotnet build -c Release',
  'dotnet publish -c Release -o /app/publish'
]

[start]
cmd = 'dotnet /app/publish/TheMindSpire.dll'

[variables]
ASPNETCORE_ENVIRONMENT = 'Production'
ASPNETCORE_URLS = 'http://0.0.0.0:8080'
